export const GAME_ACTIONS = Object.freeze({
  BOARD_CELL_CLICK: "BOARD_CELL_CLICK",
  COLLAPSE_SYMBOL_CLICK: "COLLAPSE_SYMBOL_CLICK",
  DRAW_ACCEPT: "DRAW_ACCEPT",
  DRAW_DECLINE: "DRAW_DECLINE",
  DRAW_REQUEST: "DRAW_REQUEST",
  JOIN_MATCH: "JOIN_MATCH",
  LEAVE_GAME: "LEAVE_GAME",
  LOCAL_RESTART: "LOCAL_RESTART",
  MAIN_MENU: "MAIN_MENU",
  OPEN_EXISTING_GAME: "OPEN_EXISTING_GAME",
  REMATCH: "REMATCH",
  REMATCH_ACCEPT: "REMATCH_ACCEPT",
  REMATCH_DECLINE: "REMATCH_DECLINE",
  REMATCH_REQUEST: "REMATCH_REQUEST",
  SKIP_COUNTDOWN: "SKIP_COUNTDOWN",
  START_GAME: "START_GAME"
});
